name: Build GCC cross
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Install tools
       run: |
         sudo apt-get install gcc make wget curl
       shell: bash
       
     - name: Build and upload
       env:
              GH_TOKEN: ${{ github.token }}
              GCC_VER: 13.2.0
       run: |
        git clone https://github.com/Valium007/musl-cross-make --depth 1 && cd musl-cross-make
        make -j4 && make install
        mv output arm-linux-musleabihf-gcc-13
        tar --xz -cf arm-linux-musleabihf-gcc-13.tar arm-linux-musleabihf-gcc-13/
        gh release create v$GCC_VER arm-linux-musleabihf-gcc-13.tar -R valium007/musl-cross-make -t "GCC-$GCC_VER" -n "GCC-$GCC_VER cross compiler for arm musl"
       shell: bash
       
       
